Refractor Codebase a Tweeeny Bit
ChrisChrome/ScamBaiter pull request #3
Opened 2022-04-16 17:05 UTC by greysilly7

2022-04-16 17:25 UTC, greysilly7 commented
Fixed the Temp Banning on SCam Link

2022-04-16 21:24 UTC, greysilly7 commented
Everything should work a-okay

2022-04-18 03:07 UTC, greysilly7 commented
Everything complained about should be fixed if I missed something just say "fix x thing"

2022-05-27 00:17 UTC, ChrisChrome requested changes
The latest version of this PR does NOT work properly, and scam URLs aren't detected

2022-05-27 00:17 UTC, ChrisChrome commented on bot.js
> +const client = new Discord.Client({
What did I say about making major changes like this
Please revert client back to bot

2022-05-27 00:17 UTC, ChrisChrome commented on bot.js
> +let lastIdPerGuild = [];
Okay this one was actually a good idea, no problems here lmao

2022-05-27 01:07 UTC, greysilly7 commented on bot.js
> +const client = new Discord.Client({
A var rename isnt a major change smh. BUT THIS WHOLE PR IS A MAJOR CHANGE :)

2022-05-27 17:46 UTC, merged